package com.sfd.command;

/**
 * TODO: FILL OUT
 *
 * @author Stephen Dumas - Initial Creation
 */
public enum CommandClass {
    ALARM_SILENCE(Identifier.SILENCE_ALARM, Category.APPLICATION, "0x9D"),
    ANTI_THEFT(Identifier.ANTITHEFT, Category.APPLICATION, "0x5D"),
    ANTI_THEFT_UNLOCK(Identifier.ANTITHEFT_UNLOCK, Category.APPLICATION, "0x7E"),
    APPLICATION_STATUS(Identifier.APPLICATION_STATUS, Category.APPLICATION, "0x22"),
    ASSOCIATION(Identifier.ASSOCIATION, Category.MANAGEMENT, "0x85"),
    ASSOCIATION_CONFIGURATION(Identifier.ASSOCIATION_COMMAND_CONFIGURATION, Category.MANAGEMENT, "0x9B"),
    ASSOCIATION_GROUP_INFORMATION(Identifier.ASSOCIATION_GRP_INFO, Category.MANAGEMENT, "0x59"),
    AUTHENTICATION(Identifier.AUTHENTICATION, Category.APPLICATION, "0xA1"),
    AUTHENTICATION_MEDIA_WRITE(Identifier.AUTHENTICATION_MEDIA_WRITE, Category.APPLICATION, "0xA2"),
    BARRIER_OPERATOR(Identifier.BARRIER_OPERATOR, Category.APPLICATION, "0x66"),
    BASIC(Identifier.BASIC, Category.APPLICATION, "0x20"),
    BASIC_TARIFF_INFORMATION(Identifier.BASIC_TARIFF_INFO, Category.APPLICATION, "0x36"),
    BATTERY(Identifier.BATTERY, Category.MANAGEMENT, "0x80"),
    BINARY_SWITCH(Identifier.SWITCH_BINARY, Category.APPLICATION, "0x25"),
    CENTRAL_SCENE(Identifier.CENTRAL_SCENE, Category.APPLICATION, "0x5B"),
    CLOCK(Identifier.CLOCK, Category.APPLICATION, "0x81"),
    COLOR_SWITCH(Identifier.SWITCH_COLOR, Category.APPLICATION, "0x33"),
    CONFIGURATION(Identifier.CONFIGURATION, Category.APPLICATION, "0x70"),
    CONTROLLER_REPLICATION(Identifier.CONTROLLER_REPLICATION, Category.APPLICATION, "0x21"),
    DEMAND_CONTROL_PLAN_CONFIGURATION(Identifier.DCP_CONFIG, Category.APPLICATION, "0x3A"),
    DEMAND_CONTROL_PLAN_MONITOR(Identifier.DCP_MONITOR, Category.APPLICATION, "0x3B"),
    DEVICE_RESET_LOCALLY(Identifier.DEVICE_RESET_LOCALLY, Category.MANAGEMENT, "0x5A"),
    DOOR_LOCK(Identifier.DOOR_LOCK, Category.APPLICATION, "0x62"),
    DOOR_LOCK_LOGGING(Identifier.DOOR_LOCK_LOGGING, Category.APPLICATION, "0x4C"),
    ENERGY_PRODUCTION(Identifier.ENERGY_PRODUCTION, Category.APPLICATION, "0x90"),
    ENTRY_CONTROL(Identifier.ENTRY_CONTROL, Category.APPLICATION, "0x6F"),
    FIRMWARE_UPDATE_METADATA(Identifier.FIRMWARE_UPDATE_MD, Category.MANAGEMENT, "0x7A"),
    GENERIC_SCHEDULE(Identifier.GENERIC_SCHEDULE, Category.APPLICATION, "0xA3"),
    GEOGRAPHIC_LOCATION(Identifier.GEOGRAPHIC_LOCATION, Category.APPLICATION, "0x8C"),
    HRV_STATUS(Identifier.HRV_STATUS, Category.APPLICATION, "0x37"),
    HRV_CONTROL(Identifier.HRV_CONTROL, Category.APPLICATION, "0x39"),
    HUMIDITY_CONTROL_MODE(Identifier.HUMIDITY_CONTROL_MODE, Category.APPLICATION, "0x6D"),
    HUMIDITY_CONTROL_OPERATING_STATE(Identifier.HUMIDITY_CONTROL_OPERATING_STATE, Category.APPLICATION, "0x6E"),
    HUMIDITY_CONTROL_SETPOINT(Identifier.HUMIDITY_CONTROL_SETPOINT, Category.APPLICATION, "0x64"),
    INCLUSION_CONTROLLER(Identifier.INCLUSION_CONTROLLER, Category.NETWORK_PROTOCOL, "0x74"),
    INDICATOR(Identifier.INDICATOR, Category.MANAGEMENT, "0x87"),
    IP_ASSOCIATION(Identifier.IP_ASSOCIATION, Category.MANAGEMENT, "0x5C"),
    IR_REPEATER(Identifier.IR_REPEATER, Category.APPLICATION, "0xA0"),
    IRRIGATION(Identifier.IRRIGATION, Category.APPLICATION, "0x6B"),
    LANGUAGE(Identifier.LANGUAGE, Category.APPLICATION, "0x89"),
    MAILBOX(Identifier.MAILBOX, Category.NETWORK_PROTOCOL, "0x69"),
    MANUFACTURER_PROPRIETARY(Identifier.MANUFACTURER_PROPRIETARY, Category.APPLICATION, "0x91"),
    MANUFACTURER_SPECIFIC(Identifier.MANUFACTURER_SPECIFIC, Category.MANAGEMENT, "0x72"),
    MARK(Identifier.MARK, Category.NONE, "0xEF"),
    METER(Identifier.METER, Category.APPLICATION, "0x32"),
    METER_TABLE_CONFIGURATION(Identifier.METER_TBL_CONFIG, Category.APPLICATION, "0x3C"),
    METER_TABLE_MONITOR(Identifier.METER_TBL_MONITOR, Category.APPLICATION, "0x3D"),
    METER_TABLE_PUSH_CONFIGURATION(Identifier.METER_TBL_PUSH, Category.APPLICATION, "0x3E"),
    MULTI_CHANNEL(Identifier.MULTI_CHANNEL, Category.TRANSPORT_ENCAPSULATION, "0x60"),
    MULTI_CHANNEL_ASSOCIATION(Identifier.MULTI_CHANNEL_ASSOCIATION, Category.MANAGEMENT, "0x8E"),
    MULTI_COMMAND(Identifier.MULTI_CMD, Category.TRANSPORT_ENCAPSULATION, "0x8F"),
    MULTILEVEL_SENSOR(Identifier.SENSOR_MULTILEVEL, Category.APPLICATION, "0x31"),
    MULTILEVEL_SWITCH(Identifier.SWITCH_MULTILEVEL, Category.APPLICATION, "0x26"),
    NETWORK_MANAGEMENT_BASIC_NODE(Identifier.NETWORK_MANAGEMENT_BASIC, Category.NETWORK_PROTOCOL, "0x4D"),
    NETWORK_MANAGEMENT_INCLUSION(Identifier.NETWORK_MANAGEMENT_INCLUSION, Category.NETWORK_PROTOCOL, "0x34"),
    NETWORK_MANAGEMENT_INSTALLATION_MAINTENANCE(Identifier.NETWORK_MANAGEMENT_INSTALLATION_MAINTENANCE,
            Category.NETWORK_PROTOCOL, "0x67"),
    NETWORK_MANAGEMENT_PROXY(Identifier.NETWORK_MANAGEMENT_PROXY, Category.NETWORK_PROTOCOL, "0x52"),
    NO_OPERATION(Identifier.NO_OPERATION, Category.NETWORK_PROTOCOL, "0x00"),
    NODE_NAMING_LOCATION(Identifier.NODE_NAMING, Category.MANAGEMENT, "0x77"),
    NODE_PROVISIONING(Identifier.NODE_PROVISIONING, Category.NETWORK_PROTOCOL, "0x78"),
    NOTIFICATION(Identifier.NOTIFICATION, Category.APPLICATION, "0x71"),
    POWER_LEVEL(Identifier.POWERLEVEL, Category.NETWORK_PROTOCOL, "0x73"),
    PREPAYMENT(Identifier.PREPAYMENT, Category.APPLICATION, "0x3F"),
    PREPAYMENT_ENCAPSULATION(Identifier.PREPAYMENT_ENCAPSULATION, Category.APPLICATION, "0x41"),
    PROTECTION(Identifier.PROTECTION, Category.APPLICATION, "0x75"),
    RATE_TABLE_CONFIGURATION(Identifier.RATE_TBL_CONFIG, Category.APPLICATION, "0x48"),
    RATE_TABLE_MONITOR(Identifier.RATE_TBL_MONITOR, Category.APPLICATION, "0x49"),
    SCENE_ACTIVATION(Identifier.SCENE_ACTIVATION, Category.APPLICATION, "0x2B"),
    SCENE_ACTUATOR_CONFIGURATION(Identifier.SCENE_ACTUATOR_CONF, Category.APPLICATION, "0x2C"),
    SCENE_CONTROLLER_CONFIGURATION(Identifier.SCENE_CONTROLLER_CONF, Category.APPLICATION, "0x2D"),
    SCHEDULE(Identifier.SCHEDULE, Category.APPLICATION, "0x53"),
    SCREEN_ATTRIBUTES(Identifier.SCREEN_ATTRIBUTES, Category.APPLICATION, "0x93"),
    SCREEN_METADATA(Identifier.SCREEN_MD, Category.APPLICATION, "0x92"),
    SECURITY_0(Identifier.SECURITY, Category.TRANSPORT_ENCAPSULATION, "0x98"),
    SECURITY_2(Identifier.SECURITY_2, Category.TRANSPORT_ENCAPSULATION, "0x9F"),
    SECURITY_MARK(Identifier.SECURITY_SCHEME0_MARK, Category.NONE, "0xF100"),
    SIMPLE_AV_CONTROL(Identifier.SIMPLE_AV_CONTROL, Category.APPLICATION, "0x94"),
    SOUND_SWITCH(Identifier.SOUND_SWITCH, Category.APPLICATION, "0x79"),
    SUPERVISION(Identifier.SUPERVISION, Category.TRANSPORT_ENCAPSULATION, "0x6C"),
    TARIFF_TABLE_CONFIGURATION(Identifier.TARIFF_CONFIG, Category.APPLICATION, "0x4A"),
    TARIFF_TABLE_MONITOR(Identifier.TARIFF_TBL_MONITOR, Category.APPLICATION, "0x4B"),
    THERMOSTAT_FAN_MODE(Identifier.THERMOSTAT_FAN_MODE, Category.APPLICATION, "0x44"),
    THERMOSTAT_FAN_STATE(Identifier.THERMOSTAT_FAN_STATE, Category.APPLICATION, "0x45"),
    THERMOSTAT_MODE(Identifier.THERMOSTAT_MODE, Category.APPLICATION, "0x40"),
    THERMOSTAT_OPERATING_STATE(Identifier.THERMOSTAT_OPERATING_STATE, Category.APPLICATION, "0x42"),
    THERMOSTAT_SETBACK(Identifier.THERMOSTAT_SETBACK, Category.APPLICATION, "0x47"),
    THERMOSTAT_SETPOINT(Identifier.THERMOSTAT_SETPOINT, Category.APPLICATION, "0x43"),
    TIME(Identifier.TIME, Category.MANAGEMENT, "0x8A"),
    TIME_PARAMETERS(Identifier.TIME_PARAMETERS, Category.MANAGEMENT, "0x8B"),
    TRANSPORT_SERVICE(Identifier.TRANSPORT_SERVICE, Category.TRANSPORT_ENCAPSULATION, "0x55"),
    USER_CODE(Identifier.USER_CODE, Category.APPLICATION, "0x63"),
    VERSION(Identifier.VERSION, Category.MANAGEMENT, "0x86"),
    WAKE_UP(Identifier.WAKE_UP, Category.MANAGEMENT, "0x84"),
    WINDOW_COVERING(Identifier.WINDOW_COVERING, Category.APPLICATION, "0x6A"),
    ZIP(Identifier.ZIP, Category.NETWORK_PROTOCOL, "0x23"),
    ZIP_6LOWPAN(Identifier.ZIP_6LOWPAN, Category.NETWORK_PROTOCOL, "0x4F"),
    ZIP_GATEWAY(Identifier.ZIP_GATEWAY, Category.NETWORK_PROTOCOL, "0x5F"),
    ZIP_NAMING_LOCATION(Identifier.ZIP_NAMING, Category.MANAGEMENT, "0x68"),
    ZIP_ND(Identifier.ZIP_ND, Category.NETWORK_PROTOCOL, "0x58"),
    ZIP_PORTAL(Identifier.ZIP_PORTAL, Category.NETWORK_PROTOCOL, "0x61"),
    ZWAVE_PLUS_INFO(Identifier.ZWAVEPLUS_INFO, Category.MANAGEMENT, "0x5E");

    private final Identifier identifier;
    private final Category category;
    private final String value;

    CommandClass(Identifier identifier, Category category, String value) {
        this.identifier = identifier;
        this.category = category;
        this.value = value;
    }

    public Identifier getIdentifier() {
        return identifier;
    }

    public Category getCategory() {
        return category;
    }

    public String getValue() {
        return value;
    }
}
